// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'webinar';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String SF_PRO_BOLD = 'sf-pro-bold';
  static const String SF_PRO_REGULAR = 'sf-pro-regular';
  static const String VAZIR_BOLD = 'vazir-bold';
  static const String VAZIR_REGULAR = 'vazir-regular';
}
